ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

#如果hystrix和sentinel都引入了，但是没有开启哪一个熔断器，默认会采用hystrix的;feign默认采用的也是hystrix
#如果是HystrixTimer报的异常，则是hystix熔断触发的
feign:
#  hystrix:
#    enabled: false
  sentinel:
    enabled: true
sys:
  config:
    value: dev456

spring:
  cloud:
    kubernetes:
      ribbon:
        mode: service
      discovery:
        enabled: true
      client:
        namespace: default
