ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: false
  sentinel:
    enabled: true
sys:
  config:
    value: dev456

spring:
  cloud:
    kubernetes:
      ribbon:
        mode: service
      discovery:
        enabled: true
      client:
        namespace: default
